version: '3'

services:
  webapp:
    build:
      context: .
    expose:
    - "5000"
    ports:
    - "5000:5000"
    command: python manage.py runserver 0.0.0.0:5000
  celeryworkerdefault:
    build:
      context: .
    command: celery -A webapp worker -B -E -l info --concurrency=5 -Q default -E
  celeryworkerdaemon:
    build:
      context: .
    command: celery -A webapp worker -B -E -l info --concurrency=2 -Q daemon -Ofair -E
  flower:
    build:
      context: .
    expose:
    - "5555"
    ports:
    - "5555:5555"
    command: celery -A webapp flower --port=5555